# Generated by Django 5.0.4 on 2024-05-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("cost", models.FloatField()),
                ("currency", models.CharField(max_length=10)),
                ("purchased_date", models.DateField()),
                ("completion_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
